// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrbjnkednllemtrafofj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYmpua2VkbmxsZW10cmFmb2ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3OTUxMDcsImV4cCI6MjA2MDM3MTEwN30.n2ewCcZjK16LwtGLeTqCgCWntLaLV9RnuojR57r8Zzc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);